const x = 10

try {
    x = 10
}catch(error){
    console.log(`Erro: ${error}`)
}